### ISSUE TITLE
Add Go

### ISSUE THREAD

**Issue by theodesp** [remojansen/TechLadderIO#11]
I will be willing to work on the Go ladder

**Comment by remojansen** [comment]
Hi @theodesp great to hear that! Just send a PR whenever you feel ready. I will provide you with some feedback. Please feel free to ask any questions here if you need help. The placeholder for the go ladder is already in place: https://github.com/remojansen/TechLadderIO/tree/master/technologies/go you will need to turn on [this flag](https://github.com/remojansen/TechLadderIO/blob/master/technologies/technologies.json#L64) to enable it.

**Comment by remojansen** [comment]
Done by #24
