### ISSUE TITLE
[Feature request] Checkboxes

### ISSUE THREAD

**Issue by electronicdreamer** [remojansen/TechLadderIO#12]
What do you think of checkboxes (state stored locally) next to each level to mark the user's progression?

**Comment by remojansen** [comment]
I think it is a great idea, I'm already thinking about implementing this :) In fact, I was considering not store it locally but maybe using a service such as firebase.

**Comment by remojansen** [comment]
Done :tada: 

![screencapture-techladder-io-2018-10-15-10_11_14](https://user-images.githubusercontent.com/10656223/46941333-cc6f0380-d062-11e8-9329-ed5d2fd45a13.png)
