### ISSUE TITLE
Website content not loading

### ISSUE THREAD

**Issue by daubaris** [remojansen/TechLadderIO#34]
When going to techladder it does not output any information only:
![screenshot from 2018-12-22 12-18-25](https://user-images.githubusercontent.com/16244425/50373194-c7d74600-05e3-11e9-876b-1e3b98991c11.png)

Console shows:
![image](https://user-images.githubusercontent.com/16244425/50373204-e3425100-05e3-11e9-924d-61ff8f4cd57e.png)

Occurs on firefox quantum 64.0, google chrome 71.0, did not check IE, but probably there too.

**Comment by remojansen** [comment]
Hi, @daubaris would you like to send a PR?

**Comment by daubaris** [comment]
Hi, @remojansen it seems that this doesn't occur anymore so I am closing this.
