### ISSUE TITLE
Add direct link to GitHub repo on landing page

### ISSUE THREAD

**Issue by indiescripter** [remojansen/TechLadderIO#4]
"Please open an issue or send us a PR on Github!" on the main landing page needs a direct hyperlink to the TechLadderIO repo in GH. Plus correct minor spelling error - GitHub with capital 'H'.

**Comment by remojansen** [comment]
Done by #5

**Comment by indiescripter** [comment]
Excellent round-trip process, referencing the PR number in closing the issue!
Sure you do that all the time anyway :100:
